version: '3.3'
services:
  freepbx:
    build: ./freepbx
    network_mode: host
    restart: always
    environment:
      - ADMIN_PASSWORD=admin123
    volumes:
      - backup:/backup
      - recordings:/var/spool/asterisk/monitor

volumes:
  backup:
  recordings:
